# Site settings
baseurl: "" # /gh-pages
asseturl: "/assets"
skin: "iunui"
lang:
 brandname: "iunui"
 read_more: ">>"
 showpostby: "Bài cùng mục: "
 samecat: "Xem thêm cùng mục"
 sametag: "Xem thêm cùng thẻ"
 hotpost: "Bài nổi bật"
 subcat: "Chuyên mục" # name of sub folder
# Build settings
markdown: kramdown
permalink: /:categories/:title
paginate: 8
paginate_path: /page:num

gems: [jekyll-paginate]
